version: '3.8'

services:
  broker:
    container_name: broker
    image: rabbitmq:3.9-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - network
    env_file:
      - 'variables.compose.env'

  backend:
    container_name: redis
    image: redis:7.0
    ports:
      - 6379:6379
    networks:
      - network
    env_file:
      - 'variables.compose.env'
    command: redis-server --requirepass password

networks:
    network: {}